//let b = 2

try {
    let c = 2 + b
} catch(error) {
    console.log("Algo deu errado " + error)
}

console.log('n√£o para o codigo')